version: "3.3"

services:
  butterfly_backend:
    image: prakasa1904/tps-py-api:production
    container_name: butterfly_backend
    working_dir: /devetek
    volumes:
      - ./process/dev/dev-pgql:/devetek/pgql
      - /devetek/python_modules/ # Generate volume `python_modules` empty
    restart: always
    command: "make prod-up"
    networks:
      - kepasar

  butterfly_frontend:
    image: node:lts-alpine
    container_name: butterfly_frontend
    working_dir: /devetek
    restart: always
    command: yarn start
    networks:
      - kepasar

networks:
  kepasar:
    external: true